version: '3'
services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    image: redis:6

  directus:
    image: directus/directus:11.2.2
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    env_file:
      - .env
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b44'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      PUBLIC_URL: 'http://localhost:8055'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'false'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'password'

      WEBSOCKETS_ENABLED: 'true'
      WEBSOCKETS_REST_AUTH: 'public'

      # These is helpful for local developement but should probably be removed in production
      CORS_ENABLED: 'true'
      CORS_ORIGIN: '*'
      REFRESH_TOKEN_COOKIE_DOMAIN: 'localhost, 0.0.0.0'
      REFRESH_TOKEN_COOKIE_SECURE: 'false'
      REFRESH_TOKEN_COOKIE_SAME_SITE: 'lax'
      EXTENSIONS_AUTO_RELOAD: 'true'
      EXTENSIONS_PATH: './extensions'

      # The default config prevents importing files from 0.0.0.0. See https://docs.directus.io/self-hosted/config-options.html#security . This can be removed in production but in local development it is recommended to keep it so you can import logos from Organization > website.
      IMPORT_IP_DENY_LIST: ''
